#!/usr/bin/env bash
# Runs the engine's own headless checks (tests/*.gd) standalone, with no game around it.
#
# The engine is a Godot addon, so it only runs inside a project that mounts it at res://addons/openfire_engine/. This
# script makes that project for itself: .harness/ (gitignored; a dot-directory, so a game that has the engine as a
# submodule never scans it) holds a bare project.godot and a link back to this checkout as addons/openfire_engine.
#
#   tools/run_tests.sh                 every check
#   tools/run_tests.sh mod_loading     the checks whose file name contains "mod_loading"
#   tools/run_tests.sh --clean         remove .harness/ (use this, not rm -rf: on Windows the link is a junction, and
#                                      deleting through it would delete this checkout)
#
# GODOT=<path to the Godot 4.7 binary> (default: `godot` on PATH). Exit status: the number of failing checks.
set -u
cd "$(dirname "$0")/.."
ROOT=$(pwd)
GODOT=${GODOT:-godot}
H=.harness

if [ "${1:-}" = "--clean" ]; then
	case "$(uname -s)" in
		MINGW*|MSYS*|CYGWIN*) [ -e "$H/addons/openfire_engine" ] && cmd //c "rmdir $(cygpath -w "$ROOT/$H/addons/openfire_engine")" ;;
		*) rm -f "$H/addons/openfire_engine" ;;
	esac
	[ -e "$H/addons/openfire_engine" ] || rm -rf "$H"
	exit 0
fi

if [ ! -f "$H/project.godot" ]; then
	mkdir -p "$H/addons"
	cat > "$H/project.godot" <<'PROJECT'
; Generated by tools/run_tests.sh -- a bare project that mounts this checkout as an addon, for the engine's own tests.
config_version=5

[application]

config/name="openfire-engine test harness"
config/features=PackedStringArray("4.7", "GL Compatibility")

[rendering]

renderer/rendering_method="gl_compatibility"
PROJECT
fi
if [ ! -e "$H/addons/openfire_engine" ]; then
	case "$(uname -s)" in
		MINGW*|MSYS*|CYGWIN*) cmd //c "mklink /J $(cygpath -w "$ROOT/$H/addons/openfire_engine") $(cygpath -w "$ROOT")" > /dev/null ;;
		*) ln -s "$ROOT" "$H/addons/openfire_engine" ;;
	esac
fi

"$GODOT" --headless --audio-driver Dummy --path "$H" --import > /dev/null 2>&1

failed=0
for f in tests/*.gd; do
	name=$(basename "$f" .gd)
	if [ $# -gt 0 ] && [[ "$name" != *"$1"* ]]; then
		continue
	fi
	if "$GODOT" --headless --audio-driver Dummy --path "$H" --script "res://addons/openfire_engine/$f" > "$H/$name.log" 2>&1 \
			&& ! grep -q "^FAIL\|SCRIPT ERROR\|Parse Error" "$H/$name.log"; then
		echo "pass  $name"
	else
		echo "FAIL  $name   (log: $H/$name.log)"
		failed=$((failed + 1))
	fi
done
exit $failed
